INSERT INTO coordinates (x, y, address_name) VALUES
                                                 (0, 0, 'Deadwood Junction'),
                                                 (5, 3, 'Rustler’s Hollow'),
                                                 (-7, 8, 'Broken Spur Ranch'),
                                                 (12, -4, 'Dustveil Crossing'),
                                                 (-10, 6, 'Copperhead Bluff'),
                                                 (20, 10, 'Rattlesnake Gulch'),
                                                 (-15, -5, 'Outlaw’s Refuge'),
                                                 (30, -10, 'Ironclad Ridge'),
                                                 (-12, -20, 'Bandit’s Pass'),
                                                 (50, 25, 'Silver Creek'),
                                                 (-55, 10, 'Black Rock Canyon'),
                                                 (48, 30, 'Coyote’s End'),
                                                 (-40, -15, 'Hangman’s Bluff'),
                                                 (35, 45, 'Shady Gulch'),
                                                 (-30, -40, 'Whispering Pines'),
                                                 (60, -25, 'Bison Flats'),
                                                 (-70, 35, 'Ghost River'),
                                                 (80, 20, 'Gambler’s Haven'),
                                                 (-85, -10, 'Lone Star Outpost'),
                                                 (90, -5, 'Bleeding Rock'),
                                                 (-95, 50, 'Whiskey Springs'),
                                                 (100, -15, 'Timberwolf Ridge'),
                                                 (-105, 40, 'Dead Horse Flats'),
                                                 (110, -30, 'Buzzard’s Roost'),
                                                 (-115, 15, 'Grimshaw Valley'),
                                                 (120, -50, 'Sundown Prairie'),
                                                 (-125, 60, 'Lost Trail Fork'),
                                                 (130, -20, 'Thunder Mesa'),
                                                 (-135, 35, 'Hellfire Basin'),
                                                 (140, -60, 'Gunsmoke Hill'),
                                                 (-145, 70, 'Wraithwood'),
                                                 (150, -25, 'Scorpion Bend'),
                                                 (-155, 55, 'Crimson Dunes'),
                                                 (160, -75, 'Bloodmoon Ridge'),
                                                 (-165, 80, 'Fool’s Gold Canyon'),
                                                 (170, -35, 'Dustbowl Flats'),
                                                 (-175, 90, 'Broken Arrow Bluff'),
                                                 (180, -85, 'Longhorn Crossing'),
                                                 (-185, 95, 'Vulture’s Perch'),
                                                 (190, -40, 'Gilded Sands'),
                                                 (-195, 100, 'Widow’s Rest'),
                                                 (200, -95, 'Hellhound Hollow'),
                                                 (-205, 110, 'Crow’s Nest'),
                                                 (210, -50, 'Jackal’s Pass'),
                                                 (-215, 120, 'Pale Rider’s Haven'),
                                                 (220, -105, 'Tarnished Gold Outpost'),
                                                 (-225, 130, 'Devil’s Fork'),
                                                 (230, -60, 'Snakebite Ridge'),
                                                 (-235, 140, 'Wicked Wind Bluff'),
                                                 (240, -115, 'Coffin Creek'),
                                                 (-245, 150, 'Brimstone Heights'),
                                                 (250, -125, 'Thunder Bluff'),
                                                 (-255, 160, 'Six Shooter Valley'),
                                                 (260, -135, 'Desperado’s Trail'),
                                                 (-265, 170, 'Gallows Ridge'),
                                                 (270, -145, 'Shattered Plains'),
                                                 (-275, 180, 'Vanish Point'),
                                                 (280, -155, 'Rustwater Bend'),
                                                 (-285, 190, 'Howling Caves'),
                                                 (290, -165, 'Outcast’s Rest'),
                                                 (-295, 200, 'Widowmaker’s Trail'),
                                                 (300, -175, 'Bullet Creek'),
                                                 (-305, 210, 'Serpent’s Hollow'),
                                                 (310, -185, 'Black Cactus Flats'),
                                                 (-315, 220, 'Burning Sky Mesa'),
                                                 (320, -195, 'Ashen Outpost'),
                                                 (-325, 230, 'Bleakwater Ridge'),
                                                 (330, -205, 'Forsaken Gulch'),
                                                 (-335, 240, 'Gravesend Crossing'),
                                                 (340, -215, 'Deathrattle Canyon'),
                                                 (-345, 250, 'Ember Falls'),
                                                 (350, -225, 'Reaper’s Hollow'),
                                                 (-355, 260, 'Wanderer’s Rest'),
                                                 (360, -235, 'Phantom Springs'),
                                                 (-365, 270, 'Twilight Sands'),
                                                 (370, -245, 'Sunbleached Ridge'),
                                                 (-375, 280, 'Tombstone Pass'),
                                                 (380, -255, 'Black Vulture Roost'),
                                                 (-385, 290, 'Bleeding Pines'),
                                                 (390, -265, 'Dagger Falls'),
                                                 (-395, 300, 'Specter’s Trail'),
                                                 (400, -275, 'Dustgrit Bend'),
                                                 (-405, 310, 'Bandolier Creek'),
                                                 (410, -285, 'Raven’s Watch'),
                                                 (-415, 320, 'Widow’s Bluff'),
                                                 (420, -295, 'Rogue’s Refuge'),
                                                 (-425, 330, 'Midnight Mesa'),
                                                 (430, -305, 'Sunset Hollow'),
                                                 (-435, 340, 'Reckoner’s Trail'),
                                                 (440, -315, 'Shattered Canyon'),
                                                 (-445, 350, 'Warrior’s Rest'),
                                                 (450, -325, 'Rider’s Last Stand'),
                                                 (-455, 360, 'Gritstone Gorge'),
                                                 (460, -335, 'Sable Creek'),
                                                 (-465, 370, 'Nomad’s End'),
                                                 (470, -345, 'Wayfarer’s Bluff'),
                                                 (-475, 380, 'Lone Prairie'),
                                                 (480, -355, 'Widow’s Peak'),
                                                 (-485, 390, 'Outlaw’s Hollow'),
                                                 (490, -365, 'Stonefang Pass'),
                                                 (-495, 400, 'Trailblazer’s Cross');

